### ISSUE TITLE
Makefile: Why -O0?

### ISSUE THREAD

**Issue by polluks** [batari-Basic/batari-Basic#3]
If you add debugging symbols, you don't want optimisation. Are the options mistakenly swapped?

**Comment by msaarna** [comment]
The commented ones "-g -O0" are intended only for times I periodically compile with the intent of checking things out with valgrind.

The uncommented -O0 isn't required, but not hurting anything either, since -O0 is typically the compiler default. Certainly it's the case for gcc.

**Comment by msaarna** [comment]
Just double-checked, and indeed those are swapped. I was looking at a related project for the previous answer. I'll swap those around. Thanks!
